// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"time"
)

type Good struct {
	ID          int32     `json:"id"`
	SellerID    int64     `json:"seller_id"`
	Title       string    `json:"title"`
	Price       int64     `json:"price"`
	Description string    `json:"description"`
	Image       string    `json:"image"`
	Category    string    `json:"category"`
	Rating      string    `json:"rating"`
	Discount    int64     `json:"discount"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
}
