// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"time"
)

type Good struct {
	ID          int32
	SellerID    int64
	Title       string
	Price       int64
	Description string
	Image       string
	Category    string
	Rating      string
	Discount    int64
	Status      string
	CreatedAt   time.Time
}
